server:
  port: 9093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  profiles:
    active: dev

  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true
    username: root
    password: rootpass1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
