eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant?createDatabaseIfNotExist=true
    username: root
    password: rootpass1234